### ISSUE TITLE
rollingSum is buggy.

### ISSUE THREAD

**Issue by yipjustin** [saddle/saddle#64]
Consider the following code which prints the rolling sum of a vector.
```
Vec(-1,1,3,10,300).rollingSum(3)
```
If I understand the meaning of rollingSum correctly, it should create a sliding window of size 3, and sum up all the numbers within the window. Hence, the correct result of the statement about is
```
Vec(3, 14, 313)
```
However, when I run the code, I get the following weird result:
```
Vec(3, 12, 209)
```
After some digging, it appears to me that the rolling window _always_ take the first element into account. For example, the actual value returned from rollingSum for the fourth element is -1 + 3 + 10, instead of 1 + 3 + 10.

Has anyone experience similar issue with the rolling* functions?

Thanks.

**Comment by adamklein** [comment]
Fixed, released in 1.3.4
