### ISSUE TITLE
Could you release 1.3.4 ? 

### ISSUE THREAD

**Issue by svendx4f** [saddle/saddle#66]
Hi, 

This PR closed in August contains some updates we need for our deployment. 

https://github.com/saddle/saddle/pull/63

Its content is currently only available in 1.3.4-SNAPSHOT. Could you please release 1.3.4 so that we can get the official jar from the official repo? 

Thanks!

S

**Comment by adamklein** [comment]
Will do so now. Apologies for falling off the map.
