### ISSUE TITLE
Development stopped?

### ISSUE THREAD

**Issue by sglyon** [saddle/saddle#67]
Unless I missed something, it looks like the last commit was 9 months ago. Is this project still being actively worked on?

**Comment by adamklein** [comment]
I'll take pull requests and do releases, but I don't have time to push development forward at the moment. So things are stagnant... but stable. If someone wants to take the reigns, I'd be happy to bring that person up to speed and turn the project over.

**Comment by hntd187** [comment]
@adamklein I know i'm late to the party here, but I will volunteer to take over this project and push the development forward. My email is shcarman@gmail.com if you'd like to reach out to me and we can discuss what would be necessary.

**Comment by adamklein** [comment]
Yes! That would be amazing! I've definitely been off the radar. Are you still interested?

Email me at adamklein@gmail.com

Thanks for reaching out!

**Comment by alexland** [comment]
hi: last time i checked in on this project, someone had volunteered to resume development, but seems the project is still dormant. If so, are you interested still looking for a maintainer?

**Comment by hntd187** [comment]
Hey @alexland I'm that guy you just described, I am working on it, but it's been a bit slow for me, I'm trying to just get some more recent artifacts published, you're more than welcome to help if you have time.

**Comment by pityka** [comment]
I have compiled it to 2.12.1.  https://github.com/pityka/saddle/commit/d579a5a986cfb5f7c8bf7c7e3049f2686115a849

**Comment by hntd187** [comment]
@pityka can you back out the publisher changes and put a pull request in? I'm able to publish artifacts now

**Comment by pityka** [comment]
Yes I will send a pr hopefully over the weekend. 

2017. ápr. 8. dátummal, 7:29 időpontban Stephen Carman <notifications@github.com> írta:

**Comment by hntd187** [comment]
@pityka thanks, I was trying to do this a little bit ago, but scala 2.12.0 had some issues I was having trouble figuring out. Mostly because of the hdf5 and test frameworks, but clearly just removing them works too. At least for now.

**Comment by alexland** [comment]
@hntd187 love to help. i'll scan the open issues just now. Aside from those, how can i begin helping? (Again, i haven't traversed the open issues yet, but just now, it seems filling in documentation might be a place to start, but i'll wait to hear from you and review open issues & src in the meantime)

**Comment by hntd187** [comment]
@alexland I'm at the current moment just trying to get up to speed with everything in the library. Some of the code is a bit dated, but @pityka has been kind enough to submit his scala 2.12 stuff, which should get us on a current version, then I can try and update some dependencies to current versions. As for helping, there are some branches that people have put pull requests into, let's go over them and see if we want to include those pulls in and probably at this point if we can't ping the original offers we'll have to rebase the work ourselves onto master. It shouldn't be too hard, but some people have made some nice contributions I'd like to use. Then once that's all worked out we can discuss the future. Sound good?

**Comment by alexland** [comment]
definitely

**Comment by djronde** [comment]
Hey there! We still use this library quite extensively at Novus Partners and it's nice to see some new development going on here. Coincidentally, we've just updated our internal outdated fork to mirror this repository, and we'd be happy to help push development forward.

**Comment by hntd187** [comment]
@djronde Did you have something in mind? It'd be awesome if you were developing on your internal fork.

**Comment by djronde** [comment]
Because our use cases tend to be very specialized to our code base, we don't have any direct commits affecting saddle itself but we've built a few useful abstractions on top of it which mimic more involved pandas functionality and hide a few bugs. We could give it a go at incorporating the more generally applicable ones here. I think it'll take a bit of time for us to get them into PR-able form though. In the meantime, we know the library decently well so we're happy to review outstanding prs and help move those along.

**Comment by pityka** [comment]
@hntd187 can you publish the 2.12 artifact? Is there anything blocking that?

**Comment by hntd187** [comment]
@pityka no, sorry, I'll try and get to it as soon as I can, I had to work out my release keys, let's hope this works

**Comment by hmf** [comment]
Any news on the 2.12 release? I have searched Sonatype and did not find it.
I am assuming it only takes a couple of hours to get published, so I may have missed it.
 
TIA.

**Comment by tillv** [comment]
Is it published yet or any ETA when it will be?
I'm also really interested in the 2.12 artifact.

Also appreciate you taking over the project.

**Comment by hntd187** [comment]
It's not, I'm hoping to get to it today, I tried, but I was having trouble publishing from my windows machine. I don't even know if it's possible.

**Comment by hntd187** [comment]
Okay everyone I published 1.3.6 which should be for scala 2.12, please give it some time to show up the central repo, and let me know if there are any problems.

**Comment by hmf** [comment]
@hntd187 

Appreciate the effort. Some feedback:

* Found the the library at:
  https://oss.sonatype.org/content/repositories/snapshots/org/scala-saddle/saddle-core_2.12/
* The version is: `1.3.5-SNAPSHOT`, which is curious because the `version.sbt` shows `1.3.7-SNAPSHOT`
* I was able to `update`via SBT successfully, however the IntellJ's Idea IDE complained that it could not parse the jar. Hopefully it may only be an issue with the IDE. 

Once again, thanks.

**Comment by pityka** [comment]
There is a fork of saddle here: https://github.com/pityka/saddle/ with the following changes:
- organization changed to `io.github.pityka` and version bumped to 2.0.0-M3 and up
- resurrected CI based on github actions including publishing artifacts and scaladoc
- sbt 1.3.2, rewrote build, scalafmt
- improved test coverage
- less boxing
- removed non-scala dependencies (fastutils, ejml, logging) on the core library, moved joda dependent code out of the core build
- linear algebra operations backed by netlib
- removed implicit conversions
