### ISSUE TITLE
rconcat on sorted data frame

### ISSUE THREAD

**Issue by danielkorzekwa** [saddle/saddle#70]
f1 = Frame(..).sortedRowsBy...
f2 = Frame()

f1.rconcat(f2)

Concatenation is applied to unsorted version of f1, is it expected behaviour?

**Comment by adamklein** [comment]
I can't reproduce any bug, e.g.:

    val f1 = Frame("a" -> Series(1 -> 1.0, 2 -> 2.0, 3 -> 3.0))
    val f2 = Frame("b" -> Series(1 -> 1.0, 2 -> 2.0, 3 -> 3.0))

    val f3 = f1.sortedRowsBy(s => -s.raw(0))

    f3.rconcat(f2)
    res4: org.saddle.Frame[Int,String,Double] =
    [3 x 2]
              a      b
         ------ ------
    3 -> 3.0000 3.0000
    2 -> 2.0000 2.0000
    1 -> 1.0000 1.0000
    
Can you come up with a small example?

**Comment by danielkorzekwa** [comment]
I was expecting the following new frame, simply adding a new column to some frame (not aligning on the row index)

f3.rconcat(f2)

          a      b
     ------ ------
3 -> 3.0000 1.0000
2 -> 2.0000 2.0000
1 -> 1.0000 3.0000

practical scenario:

```
/**
* @param frame [week_id:Int,offer_given:Boolean)
* @return frame [week_id,offer_given,weeks_since_offer]
*/
def addColumnWeeksSinceCustomerOffer(frame:Frame):Frame = {

val sortedFrameByWeek = .......

val weeksSinceOfferColumn = sortedFrameByWeek.mapByRow(.....)

sortedFrameByWeek.rconcate( new Frame(weeksSinceOfferColumn) // issue here due to aligning by row index

}
```

**Comment by adamklein** [comment]
It's not clear, but it does perform a join on the index that is not concatenated. It even takes a join parameter. I suppose there should be another command / option to ignore the indices entirely ...
