### ISSUE TITLE
Extract series from frame?

### ISSUE THREAD

**Issue by JeffreyBenjaminBrown** [saddle/saddle#85]
(Related: https://github.com/saddle/saddle/issues/32)

I'm just getting started with Saddle. Second on my todo list was to compute a new column from an old one. I'm stumped.

Here's some code that works:

```
import org.saddle.io._

val u = org.saddle.Series(3, 4)
val v = org.saddle.Series(1, 2)
val data = org.saddle.Frame(
  "u" -> u,
  "v" -> v)
val u2 = data.col("u").mapValues(_+10)
val v2 = data.col("v").mapValues(_+1)
```

I would like to then do something like this:
```
val data2 = org.saddle.Frame( u2, v2 )
```

I can't, though, because `u2` and `v2` are both `Frame`s. I expected them to be of type `Series`. How can I convert them?

**Comment by JeffreyBenjaminBrown** [comment]
I found something that works:
```
  data.col("v").colAt(0)
```

Is this the preferred way to extract a column as a `Series` from a `Frame`, given the column name (and not its number)?

**Comment by pityka** [comment]
You can use .firstCol. One reason is that Series[t,k] is not a map because keys can be repeated.
